### ISSUE TITLE
Flame-Scarred Lockboxes unobtainable

### ISSUE THREAD

**Issue by Wafflfries** [gamefreedomgit/Maelstrom#2372]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
 Flame-scarred lockboxes are not on pickpocket loot tables.

**How to reproduce:**

**How it should work:**
According to Wowhead the drop chance is around 25% and after 30+mins of pickpocketing I recieved 0 Flame-scarred lockboxes. 

**Database links:**
https://www.wowhead.com/item=63349/flame-scarred-junkbox#pick-pocketed-from;0+3-10+1

**Comment by sassouiabd** [comment]
I can confirm this issue i tried this location i had none after 15 min : 
https://www.youtube.com/watch?v=Grl54I0b1E4

This is a bit problematic because there is 4 BOE that can not obtained otherwise.

**Comment by Jokieh** [comment]
Ok, apparently the only place in the game where you can steal the Flame-Scarred Junkboxes is the Stonecore dungeon, everywhere else you only get around 10ish silvers from mobs (which is also very low).

The BOE epics inside are a bit stronger than the 353 pvp ones (=preraid BIS), but they are almost impossible to obtain as of now.

**Comment by sassouiabd** [comment]
@MullichWhitemane Can you look at this one please it should be just the loot table for humonoid.

**Comment by MullichWhitemane** [comment]
@sassouiabd I can only mark this issue as Medium for now as our devs have their hands full with their priority list.

**Comment by sassouiabd** [comment]
It will never be corrected early on anf pass after all the high priority.
If the correction is quick and the impact is big.
A lot of rogue items for pvp and pve progression are locked behind this
The early on of the season this is corrected the better 🙏

**Comment by MullichWhitemane** [comment]
@sassouiabd Looks like your wish has been granted - Nix has assigned this to himself.

**Comment by Jokieh** [comment]
Ok, so I saw the [commit](https://i.imgur.com/0UaOde1.png) on discord.

Tried pickpocketing in Uldum, Deepholm and Tol Barad. 

The mobs still give either silver only or have an insanely low chance for the junkbox. Only managed to get like 4 after pp-ing the whole cemetery in TB.

The issue still isn't fixed yet.

**Comment by EdyGlockenspiel** [comment]
I got 9 while questing in hyjal and only did up to the quest to kill 12 dark irons dwarves then left. 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/126888684/6ee56501-9656-41e9-b787-edc005d9b164)
That being said, it will most likely have a bugged loot table inside it anyway since pretty much every single openable item here seems to have a chance to just not have any loot whatso ever inside. 

https://github.com/gamefreedomgit/Maelstrom/issues/2839

**Comment by EdyGlockenspiel** [comment]
After opening all 9, only 2 had any items in them and it was Silver Charm Bracelet and the other had Rogue's Draught.

**Comment by bonfax4** [comment]
Did anyone ever get an epic of these ? Don't wanna waste time farming

**Comment by bugtjs** [comment]
> I got 9 while questing in hyjal and only did up to the quest to kill 12 dark irons dwarves then left. ![image](https://private-user-images.githubusercontent.com/126888684/239367838-6ee56501-9656-41e9-b787-edc005d9b164.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjg4MjMsIm5iZiI6MTcwMTMyODUyMywicGF0aCI6Ii8xMjY4ODg2ODQvMjM5MzY3ODM4LTZlZTU2NTAxLTk2NTYtNDFlOS1iNzg3LWVkYzAwNWQ5YjE2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQwNzE1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQyYWI1YTM5ZWI4ZmE3NDFkOTBiYTgyOTE2NmE0ZTRmYmJhMmY3NGZmMDhlNDE4MDhkY2U3ZDhmYWU1OWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v9E6-Mt1o_2R5Upbz7q3erQGw_Pm2cftoXGpZWS3i9Y) That being said, it will most likely have a bugged loot table inside it anyway since pretty much every single openable item here seems to have a chance to just not have any loot whatso ever inside.
> 
> #2839

main issue ive noticed is when its above 84 they dont drop it any more

**Comment by PanJanuszek** [comment]
I did some changes in % drop not much, but combined with cata retail values
Epic: 0.1%
Potion: 33%
Jewelry: 0,3%
Rings/Amulets: 0,1 - 0,3 %
